# Generated by Django 4.1.6 on 2023-04-29 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Будет использован для связи с вами в случае недоступности по номеру телефона.', max_length=254, verbose_name='Почтовый ящик')),
                ('address', models.CharField(help_text='Адрес, на который будет доставлен товар.', max_length=200, verbose_name='Адресс')),
                ('phone', models.CharField(help_text='Тел. номер, напр.: +79313261560', max_length=12, unique=True, verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
