# Generated by Django 4.1.6 on 2023-04-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=12, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
