# Generated by Django 4.2.1 on 2023-05-13 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_alter_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linked_to_promer',
            field=models.ForeignKey(blank=True, help_text='Владелец промокода, к которому привязан этот редактируемый пользователь. Поле может быть пустым.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_owner_linked_to', to=settings.AUTH_USER_MODEL, verbose_name='Владелец промокода'),
        ),
    ]
