# Generated by Django 4.2.1 on 2023-06-16 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0012_alter_profile_options_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bought_already',
            field=models.BooleanField(default=False, verbose_name='Была ли совершена хотя бы 1 покупка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linked_to_promer',
            field=models.ForeignKey(blank=True, default=None, help_text='Владелец промокода, к которому привязан этот редактируемый пользователь. Поле может быть пустым.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_owner_linked_to', to=settings.AUTH_USER_MODEL, verbose_name='Владелец промокода'),
        ),
    ]
