# Generated by Django 4.2.1 on 2023-05-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0007_product_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('goods', models.ManyToManyField(related_name='supply', to='pages.product', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Поставка товаров',
                'verbose_name_plural': 'Поставки товаров',
            },
        ),
    ]
