# Generated by Django 4.2.1 on 2023-05-18 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_product_amount'),
        ('warehouse', '0002_supplyitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={'verbose_name': 'Поставка товаров на склад', 'verbose_name_plural': 'Поставки товаров на склад'},
        ),
        migrations.RemoveField(
            model_name='supply',
            name='goods',
        ),
        migrations.AddField(
            model_name='supplyitem',
            name='supply_link',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sup_item', to='warehouse.supply', verbose_name='Ссылка на поставку'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplyitem',
            name='product',
            field=models.ForeignKey(help_text='Товар, пришедший на склад в поствке.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pages.product', verbose_name='Товар'),
        ),
    ]
