# Generated by Django 4.2.1 on 2023-05-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_supply_options_remove_supply_goods_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplyitem',
            options={'verbose_name': 'Товар из поставки', 'verbose_name_plural': 'Товары из поставки'},
        ),
        migrations.AlterField(
            model_name='supply',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации поставки'),
        ),
    ]
