# Generated by Django 4.2.1 on 2023-05-27 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_supplyitem_options_alter_supply_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyitem',
            name='supply_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sup_items', to='warehouse.supply', verbose_name='Ссылка на поставку'),
        ),
    ]
