# Generated by Django 4.1.6 on 2023-04-23 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=100, null=True, verbose_name='Код промокода')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Чей промокод')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to=pages.models.Product.directory_path, verbose_name='Фото товара')),
                ('archived', models.BooleanField(default=False, verbose_name='Архивировано?')),
                ('limited', models.BooleanField(default=False, verbose_name='Товар лимитированой серии?')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(help_text='Группа товара, по которой будет фильтроваться их список.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categ_products', to='pages.category', verbose_name='Категория')),
            ],
        ),
    ]
