# Generated by Django 4.1.6 on 2023-04-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_promocode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='percent',
            field=models.IntegerField(default=3, verbose_name='Процент скидки (%)'),
        ),
    ]
