# Generated by Django 4.1.6 on 2023-04-24 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0003_promocode_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='limited',
            new_name='is_limited',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='male_female',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('U', 'Унисекс')], default='U', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(help_text='Будет выводиться на главной странице. Максимум - 300 символов.', max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Архивирован ли товар?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Длинное описание товара. Будет выводиться на его личной странице.'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(editable=False, max_length=10, null=True, verbose_name='Код промокода'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='percent',
            field=models.IntegerField(default=10, verbose_name='Процент скидки (%)'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='promocode', to=settings.AUTH_USER_MODEL, verbose_name='Чей промокод'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=pages.models.Photo.directory_path, verbose_name='Изображение')),
                ('product', models.ForeignKey(help_text='Нужно выбрать товар, которому соответствует данная картинка.', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pages.product')),
            ],
        ),
    ]
