# Generated by Django 4.2.1 on 2023-05-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_delete_purchase_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=0, help_text='Количество товара на складе', max_length=100000, verbose_name='Кол-во'),
        ),
    ]
