# Generated by Django 4.2.1 on 2023-05-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_product_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=0, help_text='Количество товара на складе', verbose_name='Кол-во'),
        ),
    ]
