# Generated by Django 4.2.1 on 2023-05-24 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0008_alter_product_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='user',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promocode', to=settings.AUTH_USER_MODEL, verbose_name='Чей промокод'),
        ),
    ]
