# Generated by Django 4.1.6 on 2023-05-05 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_delete_purchase_alter_product_price'),
        ('orders', '0003_purchase_alter_order_created_alter_order_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=12, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='order',
            name='promocode_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.promocode', verbose_name='Использованный промокод'),
        ),
    ]
