# Generated by Django 4.2.1 on 2023-05-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_phone_order_promocode_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=12, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
