# Generated by Django 4.2.1 on 2023-05-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Оформленный заказ', 'verbose_name_plural': 'Оформленные заказы'},
        ),
    ]
