# Generated by Django 4.2.1 on 2023-05-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_delete_purchase_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OS', 'Без статуса'), ('RE', 'Отменен'), ('OTW', 'На пути к заказчику'), ('FI', 'Завершен')], default='OS', max_length=3, null=True),
        ),
    ]
