# Generated by Django 4.2.1 on 2023-05-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OS', 'Без статуса'), ('RE', 'Отменен'), ('OTW', 'На пути к заказчику'), ('FI', 'Завершен')], default='OS', max_length=3, null=True, verbose_name='Статус'),
        ),
    ]
