# Generated by Django 4.2.1 on 2023-06-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('ON', 'Оплачен онлайн'), ('NA', 'Отказ в онлайн оплате'), ('OF', 'Оплачен оффлайн'), ('NP', 'Еще не оплачен')], default='NP', max_length=2, verbose_name='Как оплачен заказ?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OS', 'Без статуса'), ('OTW', 'На пути к заказчику'), ('RE', 'Отменен'), ('FI', 'Завершен')], default='OS', max_length=3, null=True, verbose_name='Статус'),
        ),
    ]
